# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca7499058e76d74fa83cf2acdf535a94c72e81bb4e3ec7762a5e4f973d125e1c792fc0d826ff05eee7415c9e8f6d11d1c257555157951a3dad7ac96a302291a

test:
  secret_key_base: 11f193efb6bb4e749b61ac40f1f40ef9ff39274f0d8aed5eee32ea7f09d112177c8d05ac5afc62f496ee8f7319dd246c37d2ab145c5c95b32a9f7ad3c3496fa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
